---
- name: create OpenStack pool.
  command: ceph osd pool create {{ item }} {{ ceph_pool_pg_num }}
  with_items:
    - "{{ openstack_glance_pool }}"
    - "{{ openstack_cinder_pool }}"
    - "{{ openstack_nova_pool }}"
    - "{{ openstack_cinder_backup_pool }}"
  ignore_errors: True
  changed_when: False
  when: inventory_hostname == groups['ceph-mon'][0] and cephx

- name: create OpenStack keys.
  command: >
    ceph auth get-or-create {{ item.name }} {{ item.value }} -o /etc/ceph/ceph.{{ item.name }}.keyring
    creates=/etc/ceph/ceph.{{ item.name }}.keyring
  with_items:
    - "{{ openstack_keys }}"
  changed_when: False
  when: inventory_hostname == groups['ceph-mon'][0] and cephx

- name: Copy ceph.conf to the ansible server.
  fetch: src={{ item }} dest=fetch/{{ ceph_fsid }}
  when: inventory_hostname == groups['ceph-mon'][0] and cephx
  with_items:
    - /etc/ceph/ceph.conf

- name: Copy OpenStack keys to the ansible server.
  fetch: src=/etc/ceph/ceph.{{ item.name }}.keyring dest=fetch/{{ ceph_fsid }}
  when: inventory_hostname == groups['ceph-mon'][0] and cephx
  with_items:
    - "{{ openstack_keys }}"
